apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: todo-phase4
type: Opaque
data:
  database_url: {{ .Values.env.DATABASE_URL | b64enc }}
  jwt_secret: {{ .Values.env.JWT_SECRET | b64enc }}
  better_auth_secret: {{ .Values.env.BETTER_AUTH_SECRET | b64enc }}