apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: todo-phase4
data:
  NEXT_PUBLIC_API_URL: "{{ .Values.env.NEXT_PUBLIC_API_URL }}"
  NEXT_PUBLIC_APP_ENV: "{{ .Values.env.NEXT_PUBLIC_APP_ENV }}"